### PR TITLE
can now assign an id to a user ahead of registration

### PR DESCRIPTION
**Pull request by thekemkid**

### CODE REVIEW

**Comment by mirceaalexandru** [comment]
@thekemkid can you please add also tests for new feature and also to show that existing feature is not broken?

**Comment by mcdonnelldean** [comment]
Hmmm,

What is the end result here? Ultimately the value will still be `undefined` or some assigned value, right?

@thekemkid Could you give a quick round-up in the description?

**Comment by mcdonnelldean** [comment]
@thekemkid Can you take a look at this as your next task please?

**Comment by thekemkid** [comment]
Apologies on the late reply!

The end result is that the value will be some auto generated id, or some user defined id.

I can write the tests if you like, however: 

I never closed this because @rjrodger mentioned he was going to do some work on it himself when I created this PR. He only wanted it left open so he knew it had to be done. He had a really good argument as to _why_ this wasn't going to be merged, and I can't remember why. :disappointed: 

Do you want me to take another look or create a fresh PR?

**Comment by mcdonnelldean** [comment]
Closing as out of date.

**Pull request closed without merging**
