### PR TITLE
fixed tests + some cleanup + increase threshold to 76

### PR DESCRIPTION
**Pull request by ckiss**
fixes for https://github.com/senecajs/seneca-user/pull/28 + others

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
good for me :)
(after chai cleaning)

**Comment by ckiss** [comment]
thanks @AdrieanKhisbe 
chai is removed now. @mihaidma this is ready to merge now

**Comment by AdrieanKhisbe** [comment]
(eventually squash the changes so that we could fast-foward merge, or cherry-pick your commit so we don't have a merge commit)

**Comment by mihaidma** [comment]
thanks for merging Dean :+1:

**Pull request merged**
